slogan: "DETERMINATION"

show_icon: fa fa-comment-o

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All articles."
    #icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All categories."
    #icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All tags."
    #icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    #icon: "fa fa-user"
#  - title: RSS
#    url: atom.xml
#    intro: "Subscribe me."
#    # icon: "fa fa-user"

links:
  - title: 尽头之塔的访客入口
    url: https://snake.moe/
    intro: ""
    icon: false

  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

#rss: 
fancybox: true
favicon: Snake.svg
#duoshuo_shortname: 


# Analytics (change to yours)
google_analytics:
  enable: false
  siteid: UA-70812759-1


# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
#valine comment (change to yours)
#valine: 
#  enable: false
#  appId: 'xxx'
#  appKey: 'xxx'
#  placeholder: "提交评论时留下邮箱收到回复后将自动通知"
#  visitor: false
#  avatar: 'monsterid'
#  requiredFields: ['nick','mail']

  